name: socks5_io
description: IO-based socks5 library
version: 0.2.0
homepage: https://github.com/luo3house/dart_socks5_io

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
